/*
 * PAAS平台docker-yard管理系统
 * 更多信息请联系基础框架团队
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ppdai.dockeryard.client.api;

import com.ppdai.dockeryard.client.model.ImageEntity;
import com.ppdai.dockeryard.client.model.ImagePageVO;
import com.ppdai.dockeryard.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for ImageControllerApi
 */
@Ignore
public class ImageControllerApiTest {

    private final ImageControllerApi api = new ImageControllerApi();

    
    /**
     * 删除image
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteImageUsingDELETETest() throws ApiException {
        Long id = null;
        String response = api.deleteImageUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * 获取所有image列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllImagesUsingGETTest() throws ApiException {
        List<ImageEntity> response = api.getAllImagesUsingGET();

        // TODO: test validations
    }
    
    /**
     * 根据appName获取image列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getImageByAppNameUsingGETTest() throws ApiException {
        String appName = null;
        List<ImageEntity> response = api.getImageByAppNameUsingGET(appName);

        // TODO: test validations
    }
    
    /**
     * 根据id获取image
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getImageUsingGETTest() throws ApiException {
        Long id = null;
        ImageEntity response = api.getImageUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * 根据获取image列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getImagesByParamUsingGETTest() throws ApiException {
        Long repoId = null;
        String repoName = null;
        Long orgId = null;
        String orgName = null;
        String appName = null;
        String tag = null;
        Integer page = null;
        Integer size = null;
        ImagePageVO response = api.getImagesByParamUsingGET(repoId, repoName, orgId, orgName, appName, tag, page, size);

        // TODO: test validations
    }
    
}
