/*
 * PAAS平台docker-yard管理系统
 * 更多信息请联系基础框架团队
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ppdai.dockeryard.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * ImageEntity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-09T11:58:57.392Z")
public class ImageEntity {
  @SerializedName("appName")
  private String appName = null;

  @SerializedName("guid")
  private String guid = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("insertBy")
  private String insertBy = null;

  @SerializedName("insertTime")
  private OffsetDateTime insertTime = null;

  @SerializedName("isActive")
  private Boolean isActive = null;

  @SerializedName("orgId")
  private Long orgId = null;

  @SerializedName("orgName")
  private String orgName = null;

  @SerializedName("repoId")
  private Long repoId = null;

  @SerializedName("repoName")
  private String repoName = null;

  @SerializedName("tag")
  private String tag = null;

  @SerializedName("updateBy")
  private String updateBy = null;

  @SerializedName("updateTime")
  private OffsetDateTime updateTime = null;

  public ImageEntity appName(String appName) {
    this.appName = appName;
    return this;
  }

   /**
   * Get appName
   * @return appName
  **/
  @ApiModelProperty(value = "")
  public String getAppName() {
    return appName;
  }

  public void setAppName(String appName) {
    this.appName = appName;
  }

  public ImageEntity guid(String guid) {
    this.guid = guid;
    return this;
  }

   /**
   * Get guid
   * @return guid
  **/
  @ApiModelProperty(value = "")
  public String getGuid() {
    return guid;
  }

  public void setGuid(String guid) {
    this.guid = guid;
  }

  public ImageEntity id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ImageEntity insertBy(String insertBy) {
    this.insertBy = insertBy;
    return this;
  }

   /**
   * Get insertBy
   * @return insertBy
  **/
  @ApiModelProperty(value = "")
  public String getInsertBy() {
    return insertBy;
  }

  public void setInsertBy(String insertBy) {
    this.insertBy = insertBy;
  }

  public ImageEntity insertTime(OffsetDateTime insertTime) {
    this.insertTime = insertTime;
    return this;
  }

   /**
   * Get insertTime
   * @return insertTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getInsertTime() {
    return insertTime;
  }

  public void setInsertTime(OffsetDateTime insertTime) {
    this.insertTime = insertTime;
  }

  public ImageEntity isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public ImageEntity orgId(Long orgId) {
    this.orgId = orgId;
    return this;
  }

   /**
   * Get orgId
   * @return orgId
  **/
  @ApiModelProperty(value = "")
  public Long getOrgId() {
    return orgId;
  }

  public void setOrgId(Long orgId) {
    this.orgId = orgId;
  }

  public ImageEntity orgName(String orgName) {
    this.orgName = orgName;
    return this;
  }

   /**
   * Get orgName
   * @return orgName
  **/
  @ApiModelProperty(value = "")
  public String getOrgName() {
    return orgName;
  }

  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }

  public ImageEntity repoId(Long repoId) {
    this.repoId = repoId;
    return this;
  }

   /**
   * Get repoId
   * @return repoId
  **/
  @ApiModelProperty(value = "")
  public Long getRepoId() {
    return repoId;
  }

  public void setRepoId(Long repoId) {
    this.repoId = repoId;
  }

  public ImageEntity repoName(String repoName) {
    this.repoName = repoName;
    return this;
  }

   /**
   * Get repoName
   * @return repoName
  **/
  @ApiModelProperty(value = "")
  public String getRepoName() {
    return repoName;
  }

  public void setRepoName(String repoName) {
    this.repoName = repoName;
  }

  public ImageEntity tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public ImageEntity updateBy(String updateBy) {
    this.updateBy = updateBy;
    return this;
  }

   /**
   * Get updateBy
   * @return updateBy
  **/
  @ApiModelProperty(value = "")
  public String getUpdateBy() {
    return updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public ImageEntity updateTime(OffsetDateTime updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(OffsetDateTime updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageEntity imageEntity = (ImageEntity) o;
    return Objects.equals(this.appName, imageEntity.appName) &&
        Objects.equals(this.guid, imageEntity.guid) &&
        Objects.equals(this.id, imageEntity.id) &&
        Objects.equals(this.insertBy, imageEntity.insertBy) &&
        Objects.equals(this.insertTime, imageEntity.insertTime) &&
        Objects.equals(this.isActive, imageEntity.isActive) &&
        Objects.equals(this.orgId, imageEntity.orgId) &&
        Objects.equals(this.orgName, imageEntity.orgName) &&
        Objects.equals(this.repoId, imageEntity.repoId) &&
        Objects.equals(this.repoName, imageEntity.repoName) &&
        Objects.equals(this.tag, imageEntity.tag) &&
        Objects.equals(this.updateBy, imageEntity.updateBy) &&
        Objects.equals(this.updateTime, imageEntity.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appName, guid, id, insertBy, insertTime, isActive, orgId, orgName, repoId, repoName, tag, updateBy, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageEntity {\n");
    
    sb.append("    appName: ").append(toIndentedString(appName)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    insertBy: ").append(toIndentedString(insertBy)).append("\n");
    sb.append("    insertTime: ").append(toIndentedString(insertTime)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    orgName: ").append(toIndentedString(orgName)).append("\n");
    sb.append("    repoId: ").append(toIndentedString(repoId)).append("\n");
    sb.append("    repoName: ").append(toIndentedString(repoName)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    updateBy: ").append(toIndentedString(updateBy)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

