/*
 * PAAS平台docker-yard管理系统
 * 更多信息请联系基础框架团队
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ppdai.dockeryard.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * ImagePageVO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-09T11:58:57.392Z")
public class ImagePageVO {
  @SerializedName("content")
  private List<ImageEntity> content = null;

  @SerializedName("totalElements")
  private Integer totalElements = null;

  public ImagePageVO content(List<ImageEntity> content) {
    this.content = content;
    return this;
  }

  public ImagePageVO addContentItem(ImageEntity contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<ImageEntity>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public List<ImageEntity> getContent() {
    return content;
  }

  public void setContent(List<ImageEntity> content) {
    this.content = content;
  }

  public ImagePageVO totalElements(Integer totalElements) {
    this.totalElements = totalElements;
    return this;
  }

   /**
   * Get totalElements
   * @return totalElements
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalElements() {
    return totalElements;
  }

  public void setTotalElements(Integer totalElements) {
    this.totalElements = totalElements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImagePageVO imagePageVO = (ImagePageVO) o;
    return Objects.equals(this.content, imagePageVO.content) &&
        Objects.equals(this.totalElements, imagePageVO.totalElements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, totalElements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImagePageVO {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

